### ISSUE TITLE
Buy error

### ISSUE THREAD

**Issue by tes724** [PTDefender/Welcome#1]
Hello and thx for this great product.

It gets me an error when trying to buy your product. 

![image](https://user-images.githubusercontent.com/35220965/42073754-c9f97666-7b68-11e8-9f11-04a680129e26.png)

have tryed both chrome and IExplore

**Comment by tes724** [comment]
It worked when i used a referral link from Cryptognome

**Comment by PTDefenderDev** [comment]
@tes724 I fixed this issue earlier this morning. You were 100% correct, it had to do with referral links
