### ISSUE TITLE
New Version Release 

### ISSUE THREAD

**Issue by Dictatosaur** [PTDefender/Welcome#10]
Is there a way to follow Defender's version release?

---------------------
As far as I know current version is 1.1.0
While on Github appears version 1.0.7 :

![release](https://user-images.githubusercontent.com/40319965/42122798-eb6e45dc-7c4f-11e8-8ff4-4167ce2e5868.JPG)

**Comment by PTDefenderDev** [comment]
Github releases is definitely the best way, I will make sure they are always up-to-date going forward. 

Just updated for 1.1.0 https://github.com/PTDefender/Welcome/releases
