### ISSUE TITLE
Discord Invite Invalid

### ISSUE THREAD

**Issue by Dictatosaur** [PTDefender/Welcome#11]
Please provide a new link (or permission) to Defender's Discord channel.

![discord](https://user-images.githubusercontent.com/40319965/42122722-f048ea18-7c4e-11e8-9151-ed6ba36aebbb.JPG)

**Comment by PTDefenderDev** [comment]
@PTDefenderSales Can you handle this?

**Comment by juato4** [comment]
Invalid to me too!.

**Comment by PTDefenderSales** [comment]
https://discord.gg/tggKxz6

Should be working properly. We changed our channel names in discord and this caused dead links.
