### ISSUE TITLE
Stuck on waiting_for_buy

### ISSUE THREAD

**Issue by mjdavsge71** [PTDefender/Welcome#13]
I'm on Ubuntu 16.04 on a Vultr host, running unity desktop, PT bought the coin I was defending but PTDefender is just sitting there WAITING_FOR_BUY, I upgraded the PTDefender application to 1.1.0 but still nothing.  When I started defending the coin yesterday it split it up and put the small piece in dust.  I can see this in my trade history on Binance.  Now after PT bought the coin the dust is gone, the coin is now sitting in DCA about to sell but PTDefender never made any buy's.

**Comment by vbootstrap** [comment]
I am seeing similar behavior.  I am on BITTREX.

**Comment by PTDefenderDev** [comment]
On Bittrex it's important you update to version 1.1.0. I am working on building a logs tab in the app so you guys can see exactly whats happening, and if there are any errors. I will release that in version 1.2.0 sometime later today hopefully, at the latest end of day Sunday

**Comment by PTDefenderDev** [comment]
Released: https://github.com/PTDefender/Welcome/releases/tag/1.2.0
