### ISSUE TITLE
GUI Not Updating on Defender

### ISSUE THREAD

**Issue by CryptoBraz** [PTDefender/Welcome#14]
GUI is not updating. I sold AE twice & rebought defender still shows round 1. I've bought IOTA already & Defender shows waiting for buy. I've redownloaded defender to the newest version along with refreshing several times. 
<img width="1175" alt="screen shot 2018-06-30 at 12 24 44 pm" src="https://user-images.githubusercontent.com/35253107/42128633-d5530d0e-7c64-11e8-90c9-4f2dc6de1eeb.png">
<img width="1378" alt="screen shot 2018-06-30 at 12 51 42 pm" src="https://user-images.githubusercontent.com/35253107/42128634-daaef182-7c64-11e8-8ec8-25f4e0d7e2ba.png">
<img width="1370" alt="screen shot 2018-06-30 at 12 52 03 pm" src="https://user-images.githubusercontent.com/35253107/42128636-df6b0490-7c64-11e8-8741-c2238796c0ec.png">
<img width="1381" alt="screen shot 2018-06-30 at 12 52 14 pm" src="https://user-images.githubusercontent.com/35253107/42128637-e467690c-7c64-11e8-8264-44b13d1343c5.png">

**Comment by PTDefenderDev** [comment]
Hey @CryptoBraz the way Defender currently works, we rely on ProfitTrailer to do the buying and selling. If you use any external buying and selling Defender will not pick those up move it along. External triggers are a top priority for us to implement we simply need another week or so of data and testing before we start implementing this. Hope that makes sense

**Comment by CryptoBraz** [comment]
I may have not have been as clear as I should have my apologies but I didn't use any external buying PT was doing all the buying like normal. I shouldn't have said "I."

**Comment by PTDefenderDev** [comment]
Can you send me a screen shot of your Logs tab?

**Comment by PTDefenderDev** [comment]
I also just released 1.2.1 which tries to fix this: https://www.ptdefender.com/download

**Comment by CryptoBraz** [comment]
Sorry for the delay I'm out and about but here's some screenshots from my
mobile

**Comment by PTDefenderDev** [comment]
We are now well aware of the cause and am consolidating related issues here: https://github.com/PTDefender/Welcome/issues/19
