### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by juato4** [PTDefender/Welcome#15]
<img width="176" alt="captura de pantalla 2018-06-30 a la s 17 58 07" src="https://user-images.githubusercontent.com/35824627/42129075-eb8c3af6-7c90-11e8-8bef-d001ecc674ac.png">

9 hours left

**Comment by PTDefenderDev** [comment]
Can you download the latest version (https://www.ptdefender.com/download) and see if there's any errors in the Logs tab?

**Comment by juato4** [comment]
Yes, No Logs

**Comment by PTDefenderDev** [comment]
Hey we are well aware of the cause now, I am consolidating all related issues here: https://github.com/PTDefender/Welcome/issues/19
