### ISSUE TITLE
"Shutdown Action" disappears in some cases

### ISSUE THREAD

**Issue by MAXPROPHET** [PTDefender/Welcome#16]
I see SHUTDOWN as final option but there is no drop down to say: sell all (or) keep all as it previously did.

It is just purely blank. V1.2
latest version of CHROME.

SKYETH is in DCA -65.67%
Go to defend it... 
Screen shot accompanied.
Windows Server 2012 VPS
PTVersion 2.0.13
![current](https://user-images.githubusercontent.com/40211675/42130624-3a5accb6-7cb8-11e8-9236-186f72e81f4e.PNG)

**Comment by PTDefenderDev** [comment]
Thanks for reporting this, that component seems to be a bit unreliable so I am switching it to a simpler radio style component in the next update:

<img width="655" alt="screen shot 2018-07-01 at 9 46 42 am" src="https://user-images.githubusercontent.com/40553665/42135047-be121536-7d13-11e8-95d8-0b2e69c7dcc5.png">

**Comment by PTDefenderDev** [comment]
Should be fixed in 1.3.0: https://github.com/PTDefender/Welcome/releases/tag/1.3.0

**Comment by MAXPROPHET** [comment]
No no no.
This occurs when I try to execute  the newest version. 1.3.1

[cid:image001.png@01D4115A.0253C440]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PTDefenderDev** [comment]
Hang tight, on it

**Comment by PTDefenderDev** [comment]
@MAXPROPHET My fault I packaged 1.3.1 incorrectly, here's 1.3.2: https://github.com/PTDefender/Welcome/releases/tag/1.3.2
