### ISSUE TITLE
GUI - Not updating Coin Stats

### ISSUE THREAD

**Issue by capricciobob** [PTDefender/Welcome#17]
I have a coin that was defended perfectly, but the GUI looks like it is still on step 2. Here is the Binance trade log in an Excel sheet. It did great by the way! Nothing in the log tab for this coin. 

[Defended.xlsx](https://github.com/PTDefender/Welcome/files/2152345/Defended.xlsx)

![image](https://user-images.githubusercontent.com/889492/42130622-183be0ac-7cb8-11e8-82d5-c93f28c6d7cd.png)

**Comment by PTDefenderDev** [comment]
@capricciobob Thanks for the issue, we are aware and working through this as quickly as we can. Currently there is an issue with the ProfitTrailer API that does not return any record of a purchase being made so the UI gets stuck in the this state. Our solution will involve reading buys/sells directly from the exchange which should be significantly more reliable. I will update this issue when that system is in place

**Comment by PTDefenderDev** [comment]
I am consolidating all related issues here: https://github.com/PTDefender/Welcome/issues/19
