### ISSUE TITLE
Missing version number on Linux

### ISSUE THREAD

**Issue by mjdavsge71** [PTDefender/Welcome#18]
On the .deb package after install notice I never see a version number on the gui window, its a minor bug but like to see the version I'm running. 
![6-30-2018 11-50-27 pm](https://user-images.githubusercontent.com/8716187/42130886-9c360a92-7cc0-11e8-8322-dc6ea550dfc7.jpg)

**Comment by PTDefenderDev** [comment]
Thanks for reporting this, will definitely be fixed in next update, I'll post here when it's available

**Comment by PTDefenderDev** [comment]
I just released v1.3.0 which has a fit for this: https://github.com/PTDefender/Welcome/releases/tag/1.3.0
