### ISSUE TITLE
External Buy/Sell Triggers

### ISSUE THREAD

**Issue by PTDefenderDev** [PTDefender/Welcome#19]
Currently we rely on the ProfitTrailer [Data API](https://wiki.profittrailer.com/doku.php?id=swagger_api#api) to discover new buy and sell orders that dictate when PTDefender should "defend" your bags. This approach has surfaced 2 common issues now that a large amount of people are using the product:

1. It does not support systems that have external buy and sell triggers outside of ProfitTrailer
2. There is a major bug in the ProfitTrailer API where its missing buys/sells that it placed

Both of these issues lead to the common problem of the UI being "stuck" in `WAITING_FOR_BUY`.

Because of these issues, we are actively developing an update to PTDefender that will look for buys and sells directly from your exchange's API. This will be a much more reliable approach and solve both issues described above.

Follow this issue for progress, our goal is to release an updated application early next week.

**Comment by FerHen1981** [comment]
Nice guys! i hope you'll get it done:-) if not, i', happy you tried!

**Comment by PTDefenderDev** [comment]
Just released v1.3.0 which reads buys from the exchange: https://github.com/PTDefender/Welcome/releases/tag/1.3.0
