### ISSUE TITLE
Selling after "Start Defending"

### ISSUE THREAD

**Issue by Dictatosaur** [PTDefender/Welcome#2]
When Profit Trailer sells after Defender is ordered to "Start defending" no new "chunk" is being allocated to DCA/Pairs:

Example:
ProfitTrailer  Bought ETH for 700 USDT,
ProfitTrailer DCA'd ETH at 600 USDT, for 100% rebuy,
Defender is ordered to start defending,
ETH "chunk" is allocated to Profit Trailer
ETH is now at 610, Profit Trailer sells for profit after trailing,

The problem:
Defender does not allocate automatically new chunk to defend (to DCA or pairs and all the ETH is still in pending) at this point.

My current solution:
Stop Defending ETH
Start Defending ETH

---------------------
This happened 4 times now in 10 minutes on the same pair, 
Looks like Defender is not looking at the last DCA  before choosing a new "chunk" to defend,
I believe if this was the case, it would've sold the the whole DCA for profit and continued for the next bought price.
 
---------------------
On the 5th time of restarting the ETH 
Profit Trailer sold the whole bag as if the average buy price was 600 USDT instead of the actual 650  USDT.

Profit Trailer recorded profit while is is actually a loss.

This has never happened to me with Profit Trailer before.
I did not set Profit trailer to sell on loss.
I did not set PT Defender to sell on loss.
My PT Defender Settings:
Target %: -0.5 / -0.35
Rebuy: 100
Gain: 1.0
Action: Hold

**Comment by PTDefenderDev** [comment]
@PTDefenderSales Can you help with this?

**Comment by PTDefenderSales** [comment]
Hi @Dictatosaur 

In your example can you elaborate on what is going on in this step: "ETH 'chunk' is allocated to Profit Trailer"

For example purposes, we assume you had 100 ETH coins in your bag. 

What should be happening when you select "Defend", is your 100 coins will be broken up into two pieces. A large piece (example 98 coins) will be placed in a pending order, the small piece(2 coins) will be held back. This small amount will show up in either your PAIRS, DCA, or DUST log. 

PTDefender will then monitor ProfitTrailer for a purchase of that same coin (in your case ETH). This step is very important. Depending on where your small piece of coins landed (PAIRS, DCA, or DUST) PT will use different buying strategies. 

It sounds to me like the Defending is not actually getting implemented. Can you stop Defending this coin, check your exchange account and cancel any pending orders for this coin? 

Once you have done that, try "defending" this coin again. If you can let us know what happens step by step upon retry, that would be a great help. 

If you start "Defending" a coin that has a pending order already placed, PTDefender will not take those coins into account. When you start defending, everything must be in your available balance on your exchange.

**Comment by Dictatosaur** [comment]
These are the actual numbers from Binance:


Date                  | Pair            | Type| Side | Avg         | Price       | Filled    |Amount| Total       |   | Status

06-25 22:24:32 | ETH/USDT | Limit | Buy | 460.1200 | 460.2300 | 1.9542 | 1.9542 | 899.3769 |   | Filled
06-29 02:02:27 | ETH/USDT | Limit | Buy | 424.8800 | 424.8900 | 1.9601 | 1.9601 | 832.7800 |   | Filled
06-29 08:10:29 | ETH/USDT | Limit | Buy | 412.5100 | 413.1000 | 1.9591 | 1.9591 | 808.1400 |   | Filled
06-29 08:25:24 | ETH/USDT | Limit | Buy | 408.2200 | 408.2200 | 1.9388 | 1.9388 | 791.4700 |   | Filled

Total Filled:   7.8121
Total USDT price: 3,331.7669 
Average price here is:  426.485811 

**Point A: **

06-29 09:15:13 | ETH/USDT | Limit | Sell | -- | 436.9900 | -- | 6.9077 | -- | -- | Canceled

**Point B**

06-29 09:18:59 | ETH/USDT | Limit | Sell | 418.0000 | 418.0000 | 0.90445 | 0.9045 | 378.0700 |   | Filled

**Point C**

06-29 09:41:23 | ETH/USDT | Limit | Sell | -- | 436.9900 | -- | 6.3353 | -- |   | Canceled
06-29 09:49:38 | ETH/USDT | Limit | Sell | 416.6400 | 416.6400 | 0.57244 | 0.5724 | 238.5100 |   | Filled

**Point D**

06-29 09:53:44 | ETH/USDT | Limit | Sell | -- | 436.9900 | -- | 5.6525 | -- |   | Canceled
06-29 09:54:35 | ETH/USDT | Limit | Sell | 416.1100 | 416.1100 | 0.68276 | 0.6828 | 284.11000 |   | Filled

**Point E**

06-29 09:55:45 | ETH/USDT | Limit | Sell | -- | 436.9900 | -- | 4.7797 | -- |   | Canceled
06-29 10:04:57 | ETH/USDT | Limit | Sell | 416.0900 | 416.0900 | 0.87282 | 0.87282 | 363.18000 |   | Filled

**Point F**

06-29 10:07:43 | ETH/USDT | Limit | Sell | 414.9900 | 414.8100 | 4.77967 | 4.77967 | 1,983.51000 |   | Filled

**Point G**

-------------------------------

Point A:
At this point I've installed Defender and started defending ETH

Point B:
Defender gives ETH/USDT a buy price of 408.6
ETH/USDT goes straight to PAIRS
Profit Trailer starts trailing and sells for 418 (2.09% Profit)

Point C:
Few minutes nothing happens so I stop defending and start defending again (ETH/USDT) 

Point D:
Nothing happens so I stop defending and start defending again (ETH/USDT) 

Point E:
Nothing happens so I stop defending and start defending again (ETH/USDT) 

Point F:
Nothing happens so I stop defending and start defending again (ETH/USDT)

Point G:
ETH/USDT was sold for a total of 3247.38 USDT, average price of 415.68, (bought for 3,331.7669 USDT, on average price of 426.485811)


--------------------

Screenshot from ProfitTrailer:

![profittrailer](https://user-images.githubusercontent.com/40319965/42121776-2ab00940-7c3e-11e8-90c3-1aeb5ea9e4c2.JPG)

**It looks like I'm in profit, but in fact I'm in a loss of 84.3869 USDT.**

Screenshot from Binance:

![binance](https://user-images.githubusercontent.com/40319965/42121837-3c9b3fd4-7c3f-11e8-88f2-b36825e057be.JPG)

(On the 25th ProfitTrailer actually bought more and later StopLoss  most of it on the 27th )

**Comment by Dictatosaur** [comment]
From what I can see, if number 6 under "Short explanation" 
 doesn't happen (https://github.com/PTDefender/Welcome/wiki/Introduction), Defender reacts very poorly.

**Comment by PTDefenderDev** [comment]
If 6 doesn't happen Defender currently doesn't perform at all. For the first release we thought it was really important to leverage ProfitTrailers buying strategies so we dont risk getting you guys into an even worse bag. In a future version, once we have enough data and testing, we may look at better in-house buy strategies

**Comment by Dictatosaur** [comment]
It doesn't explain why Defender decided to to use lower average buy price instead of the real one.
Well, hopefully with the new release, the logs will provide an insight into this problem.

**Comment by milanl71** [comment]
Has this been solved? Happened to me on a few coins already!

**Comment by PTDefenderDev** [comment]
We made some important infrastructure changes last night to remedy this.

Please download v1.4.2: https://www.ptdefender.com/download
