### ISSUE TITLE
Invalid API key, IP or permissions for action

### ISSUE THREAD

**Issue by carllewis1980** [PTDefender/Welcome#22]
Since the Binance issue i can no longer use Defender. It comes up with an error message 

Invalid API key, IP or permissions for action

Any ideas? I have obviously changed all my API's and added my VPS IP address to the Binance whitelist

**Comment by carllewis1980** [comment]
Hi – I have tried this but Binance has flagged it as an illegal IP address

**Comment by PTDefenderDev** [comment]
Okay that is not good, I'm working on this ASAP

**Comment by PTDefenderDev** [comment]
Okay I just went through the full process of creating my new API keys in Binance, registering them with ProfitTrailer on Discord, and then Whitelisting my current and PTDefender IP address. I didn't get any errors from Binance and my current setup looks like this:

<img width="672" alt="screen shot 2018-07-04 at 11 01 04 am" src="https://user-images.githubusercontent.com/40553665/42284246-e86609e2-7f79-11e8-878f-a5a23234c4fa.png">

After that I started up ProfitTrailer, then started PTDefender, re-logged in and started defending a new coin. As far as I can tell everything seems to be in order.

Do you mind sending me a screenshot of any errors your seeing? (And please dont include api keys in the screenshot)

**Comment by carllewis1980** [comment]
See screen shot attached.

 

Or is it that I am not editing the whitelist from the VPS (IP) and am editing it from home. Different IP

**Comment by PTDefenderDev** [comment]
@carllewis1980 I dont think I can see screenshots when you reply to Github through email, can you send them to me directly at dev@ptdefender.com?

**Comment by PTDefenderDev** [comment]
We solved just solved this. When entering the list of IP addresses you need so ensure there are NO spaces anywhere in the text box: leading, trailing and spaces in between numbers and commas all need to be removed.

**Comment by nynyusa** [comment]
OK, I am frustrated since yesterday on this same issue! 
1) I cannot for the life of me find ANYWERE inside the Binance Website where to "whitelist" any ip addresses!

2) Out of frustration, I tried to install PTD again on my server...AND now I dont have my LICENSE number on the License key field!!! I checked my registration email (the one I used to register PTD) and all I have is a Welcome email WITH NO LICENSE KEY!!!

I need to fix the above 2 issues. Please help!

**Comment by carllewis1980** [comment]
I am nothing to do with PT defender and I’m sure someone from PTD will respond swiftly as they did with me.

The whitelisting is not essential. It is on the Binance create API page. The is a small section under that you can specify IP address that can control your account.

Remember to remove whitespaces
