### ISSUE TITLE
Still having Issues AFTER Binance Management Update!

### ISSUE THREAD

**Issue by nynyusa** [PTDefender/Welcome#23]
OK, I am frustrated since yesterday on this same issue!

I cannot for the life of me find ANYWERE inside the Binance Website where to "whitelist" any ip addresses!

Out of frustration, I tried to install PTD again on my server...AND now I dont have my LICENSE number on the License key field!!! I checked my registration email (the one I used to register PTD) and all I have is a Welcome email WITH NO LICENSE KEY!!!

I need to fix the above 2 issues. Please help!

**Comment by AndrewBarba** [comment]
Ok the "whitelist" should like just like this:

![42284350-47472216-7f7a-11e8-8b30-138b0053352c](https://user-images.githubusercontent.com/1316152/42293749-576921c8-7faa-11e8-85bc-ed2b80c7bb9e.png)

Your ProfitTrailer license and PTDefender license are different, if you can't find the email from PTDefender with your license, shoot me an email at dev@ptdefender.com from the email that you used to originally purchase. I'll get the license sent over to you asap

**Comment by PTDefenderDev** [comment]
Confirmed over email this is closed
