### ISSUE TITLE
Unable to get past activation screen (Linux)

### ISSUE THREAD

**Issue by cryptomonst3r** [PTDefender/Welcome#25]
I am unable to get past the activation screen once I have entered my license and selected my 'application.properties' file. The gui begins to draw the next screen and then immediately returns to the activate screen.

Environment:
    Ubuntu 16.04 server VPS
    Xfce desktop
    PTDefender .snap v1.4.3

Attempted fixes:
- Uninstall and reinstall of the snap package, making sure that the ptdefender directory is removed from '/var/snapd/'
- Installed as user, and sudo with no change in behavior.
- Verified that the api token being sent matches in the 'application.properties'
- Can see api calls to PT are responding with '401 (unauthorized)' in dev mode. Screenshot will be attached.

![ptdefender_linux_errors](https://user-images.githubusercontent.com/40868775/42341173-046ea7e8-8047-11e8-91d1-f7eb156498e7.png)

**Comment by PTDefenderDev** [comment]
@cryptomonst3r Thanks for submitting this. What version of ProfitTrailer are you running? 

And in your application.properties file you can confirm there's a line that matches: `server.api_token = ...`?

**Comment by cryptomonst3r** [comment]
@PTDefenderDev I am using PT 2.0.13, which is the latest in their releases.
I did verify that the 'application.properties' file has the 'server.api_token = ... ' line that matches the api calls from PTDefender.
I have restarted ProfitTrailer multiple times throughout the whole process.

Let me know if there is anything else that you need to help debug.

**Comment by PTDefenderDev** [comment]
Can you try hitting the api directly from your browser? Paste into the address bar:

```
http://localhost:8081/api/data?token={you api token}
```

And let me know if that works?

I wonder if there's an extra space before or after the token in the properties file?

**Comment by cryptomonst3r** [comment]
It gives a message that something went wrong when pasting directly into the address bar.

I checked and there was not an extra space before or after the token in the 'application.properties' file.

**Comment by PTDefenderDev** [comment]
@cryptomonst3r When you pasted directly into browser, PT was running right? You don't use SSL by any chance do you? If pasting into the browser directly isn't working then thats actually an issue with PT, since thats their API. It might be best to hop into the Discord (https://discord.gg/C3gwWcP) and get help from someone who knows PT a lot better and can maybe clear the cache or something

**Comment by cryptomonst3r** [comment]
So, I have started with a completely clean bot.

1. I was able to make api calls to PT with a blank 'server.api_token'value as well as '12345'.
2. I stopped the bot, then applied my PAIRS, INDICATORS, and DCA settings. API calls still worked.
3. I activated my PTD from the GUI, and was taken back to the activate screen after a flash of the next screen.

I found that after activating PTD, my applications.properties file was changed (flattened), and api calls no longer worked. I replaced my applications.properties with the version prior to PTD mangling the file, and api calls no longer work.

What is the activation doing? It seems that it is behaving badly and making changes that break the PT API.

**Comment by PTDefenderDev** [comment]
That's really helpful insight, thank you, I'm looking into this right now.

If an `server.api_token` already exists then it's supposed to just move on and use whats there. Since you set on yourself I would have expected it to do that, I'm retesting this. I also realized that the token I generate if its not there has `-` in it, and the docs say to only use letters and numbers, I'm going to adjust this now and send you a beta to try

**Comment by PTDefenderDev** [comment]
Do you mind emailing me (dev@ptdefender.com) a before and after of you application.properties file? And of course please change all keys/licenses to `xxx`. If you don't want to do that no problem, just figured it could help make diagnosing easier.

**Comment by PTDefenderDev** [comment]
Here's a beta that generates the token without any dashes:

https://pt-defender-downloads.s3.amazonaws.com/1.5.2-beta.1/ptdefender_1.5.2_amd64.snap

**Comment by cryptomonst3r** [comment]
Ok, I got it working. Once I got my server.api_token set, I had to use pm2 to remove the bot form it's list. Once I started it again, the api started working. PTD is now running.

I will test the beta with my other VPS to see if the generated api works without dashes.

**Comment by PTDefenderDev** [comment]
Going to close this now that 1.5.2 has been released
