### ISSUE TITLE
Failed to start defending

### ISSUE THREAD

**Issue by kirkelrain** [PTDefender/Welcome#26]
After the binance API_Key changes i cant start defending.

I know to put your ip 34.233.244.208 on the whitelist, but i set my API-Keys to unrestricted to any IP-Adress just for the purpose of being absolutely sure.

But still i cant start defending.
There must be some issue with the binance API settings. 
Please help

**Comment by kirkelrain** [comment]
Thanks it worked

**Comment by PTDefenderDev** [comment]
Awesome glad to hear it
