### ISSUE TITLE
Doesn't work with Profit Trailer and SSL configured

### ISSUE THREAD

**Issue by jjrich** [PTDefender/Welcome#27]
I have SSL configured for Profit Trailer, and PT Defender doesn't seem to work with SSL. When SSL is enabled on PT, Defender gets stuck "Waiting for Profit Trailer..." I am using a valid cert through Let's Encrypt.

**Comment by PTDefenderDev** [comment]
@jjrich Yes I'd love to get this working, shouldn't take much. Can you tell me what the hostname is when you're using SSL? For example, non-ssl users are all on http://localhost:8081, whats your host look like? Is it just https://localhost:443? I just need to know what lines in the application.properties file indicate that you are using SSL and I can support this very easily

**Comment by jjrich** [comment]
I use a cert that has a FQDN and I access it from the outside using that. When locally on the host though I use https://localhost:8081. There is nothing that specifies the URL, the application.properties just adds these lines to indicate SSL.

server.ssl.key-store=/C\:/Path/to/keystore.p12
server.ssl.key-store-password= xxxxxxxxxxxxxxxx
server.ssl.key-password=xxxxxxxxxxxxxxxx
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcatKeystore

**Comment by PTDefenderDev** [comment]
@jjrich Thanks for that, will have an update out sometime today with SSL support

**Comment by jjrich** [comment]
Just FYI it is still not working for me. The console is trying to load the https page but it is getting an error, net::ERR_INSECURE_RESPONSE

When I load the URL it is complaining about I get a certificate warning (as expected) but the page loads successfully. Maybe it needs to be told to ignore the hostname mismatch that is in the certificate?

**Comment by AndrewBarba** [comment]
@jjrich Yup that sounds right. The other thing we could do is support a new property in the application.properties file like:

```
server.ssl.hostname = www.yourcustomname.com
```

And then I can use that instead of localhost. Thoughts on that?

I have to see if I can avoid the hostname mismatch without that, looking into it now

**Comment by PTDefenderDev** [comment]
@jjrich Yup that sounds right. The other thing we could do is support a new property in the application.properties file like:

```
server.ssl.hostname = www.yourcustomname.com
```

And then I can use that instead of localhost. Thoughts on that?

I have to see if I can avoid the hostname mismatch without that, looking into it now

**Comment by jjrich** [comment]
I'm totally fine with that, but based on the convo that is going on in the CryptoGnome discord it seems you want to get away to modifying config that may apply only to PTD ;) The other issue is that if others use self-signed certificates they may end up with the same error I have even if the hostnames match the URL PTD uses, as it is still "Untrusted"

**Comment by PTDefenderDev** [comment]
Yup thats a fair point. It's using axios to send requests, so I can try just setting the `rejectUnauthorized` param described here: https://github.com/axios/axios/issues/535

Do you see any reason that wouldn't be sufficient?

**Comment by jjrich** [comment]
Actually reading the thread further, it may fix the issue for self-signed certs, but mine may be seen as invalid since it is a hostname mis-match, so for ultimate compatibility we may need to either

1. Also set that param and the other they are mentioning: process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
Which will allow just about anything, but it's also dangerous, [so maybe not recommended]
-or-
2. Include server.ssl.hostname = www.yourcustomname.com in the applications.properties that you can use to form your requests.

I'm more than happy to test where setting the first param gets us, and I can try with both the self signed and CA signed certs to make it as compatible as possible and we can figure it out from there.

**Comment by jjrich** [comment]
BTW I am on Windows for the test build

**Comment by PTDefenderDev** [comment]
@jjrich Here's a beta: https://pt-defender-downloads.s3.amazonaws.com/1.5.1-beta.1/PTDefender_Setup_1.5.1.exe

If you could first test without changing anything in properties thatd be great. If that doesn't work, then it also supports:

```
server.hostname = www.customdomain.com
```

I went with `server.hostname` instead of `server.ssl.hostname` becasue technically it can be used in both regardless of ssl. Hopefully it works without this though as I'd like to remove it

**Comment by jjrich** [comment]
Great, testing now, give me like 30 minutes to play with it.

**Comment by jjrich** [comment]
Okay so here is my findings.

1. Using a certificate signed by an external CA with a custom FQDN hostname
    a. Did not work with 1.5.1 out of the box.
    b. Did work once adding the server.hostname param.
2. Using a self signed certificate with FQDN and defining the server.hostname did not work
3. Using a self signed certificate with the CN of localhost does not work.

The error I get when it doesn't work is still net::ERR_INSECURE_RESPONSE

It seems that the param that was set didn't do much, but the server.hostname param helps. It helps in my situation, as I used a certificate signed by a trusted CA, but if anyone uses self signed SSL they will still have problems, no matter the hostname.

**Comment by PTDefenderDev** [comment]
Okay really good to know, thanks a ton for testing that. The app is built on electron, so I'm going to give something else a shot:

https://electronjs.org/docs/api/app#event-certificate-error

Will update you when I have another beta to test

**Comment by PTDefenderDev** [comment]
Here's a beta that listens for the cert error:

https://pt-defender-downloads.s3.amazonaws.com/1.5.1-beta.2/PTDefender_Setup_1.5.1.exe

**Comment by jjrich** [comment]
Not sure what else you changed but everything is working now. All certs are working without the server.hostname param set.

Works	Cert FQDN
Works	Cert FQDN with server.hostname defined
Works	Self Signed Cert CN=localhost
Works	Self Signed Cert CN=FQDN

**Comment by PTDefenderDev** [comment]
That's great! Going to release 1.5.1 with those changes. Thanks again for testing this, you've been a huge help

**Comment by jjrich** [comment]
My pleasure thanks!

**Comment by PTDefenderDev** [comment]
Released: https://github.com/PTDefender/Welcome/releases/tag/1.5.1
