### ISSUE TITLE
Command line version to run on Linux VPS?

### ISSUE THREAD

**Issue by rbkuhn** [PTDefender/Welcome#3]
Will there be a linux command line version in the future that I can run on a linux VPS?

**Comment by PTDefenderDev** [comment]
@rbkuhn This is definitely something we will be working on soon but right now we require an OS with a GUI. I need to focus on the GUI for now to limit the scope of development issues. Also an CLI app would require me to come up with a new way to start defending coins and monitor progress which is simply easier to do in a GUI application right now. We will support automatically defending coins that reach a certain -% and that will be a big first step towards a CLI option. Hope that makes sense
