### ISSUE TITLE
Ability to view/change settings of defended pairs.

### ISSUE THREAD

**Issue by jjrich** [PTDefender/Welcome#30]
Would be cool if you could view current settings for a defended pair, and even cooler if you could change the settings without having to stop and start defending that coin pair.

**Comment by PTDefenderDev** [comment]
Yup very doable, thanks for the idea

**Comment by flybuzz** [comment]
Second this, I think we should be able to adjust the percentage based on how big or small the bag is. Keep stopping and restarting to adjust the settings are slow.

**Comment by PTDefenderDev** [comment]
I just started working on this

**Comment by PTDefenderDev** [comment]
Released: https://github.com/PTDefender/Welcome/releases/tag/1.11.0
