### ISSUE TITLE
Seeing a lot of pairs ending up with lost bought prices

### ISSUE THREAD

**Issue by djbadders** [PTDefender/Welcome#31]
I know this is a Profit Trailer issue but PT Defender seems to trigger it. It looks like if PT Defender tries to make a purchase but it is only partially fulfilled the bought price gets lost, which is a real PIA. See errors in the log about insufficient balance, but if that is the case why did PTD even try to make the purchase? It seems PTD could be doing more here to stop this occurring, but PT obviously still have issues even on 2.14

**Comment by djbadders** [comment]
So I raised the issue with the Profit Trailer team and they said it was a PT Defender issue; please take a look at the following ticket for a better understanding of what is happening and logs. This happened to me 9 times today and has taken ages to sort out the mess. To make matters slightly worse when pressing the Reset Price button for QLC after this issue it recalculated the price incorrectly, it was much lower than it should have been. Luckily I managed to catch that in time.

The ticket for PT was: https://github.com/taniman/profit-trailer/issues/1966#issuecomment-403908055

Thanks

**Comment by PTDefenderDev** [comment]
@djbadders Thanks for the super detailed logs in the other tickets. I'm going to go through those now and see what I can find.

All of yesterday we  were investigating our bought price calculation not matching PT's bought price calculation and we think we finally have something that matches. We switched to a FIFO weighted average calculation, and from what we can tell based on testing last night, it's matching exactly what PT is calculating. 

Would you be willing to test a beta? If so what file/os do you need?

**Comment by PTDefenderDev** [comment]
To be clear, the biggest discrepancy we've seen is when orders partially fill. This beta correctly calculate the bought prices in those cases, but we're still working through PT losing the bought price. Any time we place/cancel/buy we delay 10 seconds before issuing a hotconfig for dca buy times and the bought price. The problem is, sometimes PT is more delayed than that and we end up issuing too early and then it loses the price right after. 

This beta doesn't solve that exact case yet, but I'm working on it tonight and will report back

**Comment by djbadders** [comment]
Sure I'll test a beta; I am running the Ubuntu release and I use the .deb file to install

**Comment by djbadders** [comment]
Also can I ask a quick question as I didn't find the answer in the wiki. After the price calculation issue the pair shows with a status of CANCELLED. I assume that you have to stop defending the pair and start again if this happens?

**Comment by PTDefenderDev** [comment]
Here's the deb beta: https://pt-defender-downloads.s3.amazonaws.com/1.6.0-beta.1/ptdefender_1.6.0_amd64.deb

And yes, you would have restart. There should be a red log in the logs as to why it was canceled. We're hoping the calculation changes we're making with fix a lot of those

**Comment by djbadders** [comment]
Ok running two instances of 1.6.0 now; will let you know how it goes

**Comment by PTDefenderDev** [comment]
@djbadders We just pushed more backend changes that would also effect some bought price calcs. If you saw anything weird in your testing in the past hour or so, might be worth restarting those defending coins

**Comment by djbadders** [comment]
Unfortunately PTD went very wrong after these changes and lost me 0.05283713855 BTC in potential value as it set the entire bag for AION to the current trading price and PT then sold it. I have included a screens shot of the Binance trade history for AION below. I think it would be reasonable to compensate me back the AION it mispriced which was 173.95 AION. I have stopped both instances of PTD for the moment as obviously there are some issues that need resolving here. I will dig out the PT logs later because I am at work at present. On the other instance of PTD 3 prices were lost overnight, again I will dig out the logs later.

![image](https://user-images.githubusercontent.com/34887832/42621937-011f01b2-85b7-11e8-8009-fd1bf6a95330.png)

**Comment by PTDefenderDev** [comment]
@djbadders Thanks for the updated info. Going through all the logs on our end to understand whats going on. If you can, please email us (support@ptdefender.com) your AION trade history (not order history) and logs from PT. If you had incorrect bought prices before, did not reset them, and then ran the beta, the beta would update the bought prices at some point to the correct value which could cause PT to sell if it was previously using an incorrect price. My goal is to fully understand the bought price that the old and new versions used and then take it from there. Working on this all day

**Comment by PTDefenderDev** [comment]
@djbadders I'm curious how you came up with the loss of 0.05 BTC. Looks like PT sold at .000147 and the price of the coin is now at .000144. My guess is PT was trailing the coin down and properly sold. You have the BTC to actually buy more coins than you had before. We're just getting into the logs on our end, but wanted to point that out

**Comment by djbadders** [comment]
Will email trade history for AION and PT logs when I get home.

**Comment by djbadders** [comment]
@PTDefenderDev I have emailed the PT logs to you

**Comment by PTDefenderDev** [comment]
@djbadders I have a full write up I’ll be posting tomorrow about what’s going on as well as a new version of Defender that solves the bought price issues. Thanks again for cooperating with us.

**Comment by juato4** [comment]
REAL BTG_bought_price = 0.08355478


PTD:

<img width="1354" alt="captura de pantalla 2018-07-13 a la s 11 04 27" src="https://user-images.githubusercontent.com/35824627/42695743-ab283bc6-868c-11e8-93dc-0122cf2f02a3.png">

**Comment by PTDefenderDev** [comment]
@juato4 @djbadders As promised: https://github.com/PTDefender/Welcome/issues/32
