### ISSUE TITLE
Pending % sale

### ISSUE THREAD

**Issue by whytewolf69** [PTDefender/Welcome#33]
Can we either have an increase in the PTDefender places a limit sell order on the exchange at a 1% gain from your original buy price. Or the option to be able to set the pending sell order price. There may be a case if you get a spike in price greater than 1% you may end up selling the bag at a lose.

**Comment by PTDefenderDev** [comment]
Can you explain this more? Is the "Percent Gain" option that we already have not what you're looking for? I'm also not sure what you mean by "if you get a spike in price greater than 1% you may end up selling the bag at a lose".

If we're placing the sell order for 1% higher than your starting bought price, it definitely can't sell at a loss. But I'm guessing you mean it wont sell at the optimal trailing price. Would have to think about to do there
