### ISSUE TITLE
Pop-ups aren't visible if scrolled down a list

### ISSUE THREAD

**Issue by djbadders** [PTDefender/Welcome#34]
In PTD 1.7.0 if you are scrolled down a list of pairs and then click "Start" to start defending the pop-up renders at the top of the list where it is not visible and therefore it confuses the user. Other pop-ups do similar.

**Comment by PTDefenderDev** [comment]
Thanks will get this fixed

**Comment by PTDefenderDev** [comment]
Fixed: https://github.com/PTDefender/Welcome/releases/tag/1.7.1
