### ISSUE TITLE
Display name of the bot in session window title

### ISSUE THREAD

**Issue by Ronanza** [PTDefender/Welcome#36]
Hi,

it would be very convenient, if the name of the bot as set in „server.sitename“ from PT application.properties would be displayed in the title bar of the respective session window.

Thanks,
Ronanza

**Comment by PTDefenderDev** [comment]
Awesome great idea, will add this

**Comment by Ronanza** [comment]
Cool!

**Comment by PTDefenderDev** [comment]
Good news, launching in next beta:

<img width="999" alt="screen shot 2018-07-17 at 10 35 32 pm" src="https://user-images.githubusercontent.com/40553665/42856151-d80fefac-8a11-11e8-98a4-2dc4864b6331.png">

**Comment by Ronanza** [comment]
Awesome. It would be nice to display it in the title bar also. This would be helpful for switching between instances in Windows. Making it easier to select the right stacked application window from the task bar .

**Comment by PTDefenderDev** [comment]
Added it to the title bar! Will be released in the next hour or so

**Comment by Ronanza** [comment]
Perfect. Thanks for the excellent work...

**Comment by PTDefenderDev** [comment]
Thank you! Released: https://github.com/PTDefender/Welcome/releases/tag/1.9.0
