### ISSUE TITLE
Minor - Average spelled incorrectly when PTD detects that PT and PTD average differ

### ISSUE THREAD

**Issue by cryptomonst3r** [PTDefender/Welcome#37]
Just a minor error with the spelling of 'Average' which reads as 'Avergae' in the message displayed when PT and PTD average do not match.

![averagespellingerror](https://user-images.githubusercontent.com/40868775/42776488-0450b622-88ec-11e8-921d-ba495e784f99.JPG)

Cheers!

**Comment by PTDefenderDev** [comment]
Aww man, I'm so bad at spelling. Will get this fixed thank you

**Comment by cryptomonst3r** [comment]
It happens to us all. Glad it's an easy one compare to some of the issues lately. :)

**Comment by PTDefenderDev** [comment]
Fixed in beta, will be released in the next day or two!
