### ISSUE TITLE
Average calculation error when both stopping and during defending

### ISSUE THREAD

**Issue by djbadders** [PTDefender/Welcome#39]
The pair POWRBTC has had its average price miscalculated by PTD 1.8.0 both during defending and after I had stopped defending. 

When I started defending the following was logged by PTD: "Attempting SELL order: price=0.000056503339 quantity=326.2023998797187" , so as I use 1% gain PTD started with a average price of 0.0000559439

![image](https://user-images.githubusercontent.com/34887832/42784810-3de68734-8948-11e8-8c9f-2cc89944b506.png)

It then ran several rounds, when I decided to stop and switch bags; when I stopped the average price set was a lot less than I was expecting at 0.00004970, so I decided to recalculate the price manually.

The PTD logs for POWR were:
![image](https://user-images.githubusercontent.com/34887832/42784916-8d3e2c9c-8948-11e8-8b60-7e22d49dfd55.png)

Calculating the price using an extract from Binance for order history of POWR allowed me to find the last 0 balance point and then calculate the average price forwards from there which gave me 0.00005590022364217 , which was far more realistic.

My workings were:
![image](https://user-images.githubusercontent.com/34887832/42785044-e6d1cbba-8948-11e8-821c-67cb83d73b71.png)

So to me it looks like the average calculations are off during defending as the last pending sell order on POWR set a price of 0.00005280 which minus the 1% gain is 0.00005226732 , which is lower than the real average price, and the average price when stopping defending was significantly lower still at 0.00004970

I think there are still issues here that need looking at urgently.

Thanks

**Comment by djbadders** [comment]
Trade history from Binance
![image](https://user-images.githubusercontent.com/34887832/42785289-dbfea9d2-8949-11e8-8292-f5055f76062c.png)
![image](https://user-images.githubusercontent.com/34887832/42785308-f00f1bf0-8949-11e8-95ef-8f6e76b41a23.png)

**Comment by PTDefenderDev** [comment]
But if you stopped defending then the only thing we can really set your avg price to is the bought price you told us at time of start, plus any new buys after that point. You would have a handful of buys near the current price of coin so we have to take those into account when stop defending. Your new weighted average would start with the price you gave on start and balance when you started, plus the weighted averages of any buys after that point. Does that not seem right?

**Comment by djbadders** [comment]
The theory seems right but the calculations are off IMO; for instance the last pending sell was set at a price of 0.00005280 which minus the 1% gain is 0.00005226732, so I would have expected the average price to be set to this when stopping defending, as the last pending sell price should be the weighted average plus 1%. The price PTD actually set was 0.00004970 ???

**Comment by PTDefenderDev** [comment]
Okay this is making sense, you're right. What we need to do is store the datetime when you move to next round And only weighted average buys after that point, along with your original buy price. So if you go through 3 rounds, and are now waiting for buy and you stop it, easy no buys after the last round change so we set to initial price. If you go through 3 rounds, and then PT buys, we buy, and you are waiting for sell and then cancel, we need to weighted average the initial buy plus those 2 extra buys.

Does this seem right to you? It's a relatively easy change on our backend to do this

**Comment by djbadders** [comment]
I think so, try working the math through with my figures to see if you can them to match.

**Comment by djbadders** [comment]
At the end of the day you need to be sure before updating as this is peoples bot holdings that are getting miscalculated prices and could result in serious financial losses. I have had to spend many hours watching and recalculating prices as unfortunately, but I am hoping this will fix this issue.

**Comment by PTDefenderDev** [comment]
We have two pending UI fixes and I just wrote this fix on the backend. Haven't deployed anything today because for the past 6 hours I've been writing integration tests with different bags that people have been sending us, yours included. There's now an integration test on our backend for exactly this case.

Despite the issues I hope you understand I am taking this extremely seriously. Have been working essentially non-stop for the past 4 days on these issues and new test cases. I'm not making any excuses for previous issues, but trust me I'm doing everything I can to get this as stable as possible. We're currently on day 16 of this being on sale, I want it completely stable just as fast as everyone else.

**Comment by PTDefenderDev** [comment]
Just released the fix for this on the backend

**Comment by djbadders** [comment]
Thanks
