### ISSUE TITLE
PTD seems to have missed sales occurring

### ISSUE THREAD

**Issue by djbadders** [PTDefender/Welcome#40]
I am defending 3 bags on my of my bots and it seems to have missed the fact that PT has sold the pairs, as it is still in WAITING_FOR_SELL status on 2 bags even though the bot hasn't got any apirs to sell for those bags. See below:
![image](https://user-images.githubusercontent.com/34887832/42801775-a4917dfe-8998-11e8-8b23-0c7b3cb256db.png)

The PTD logs show the last buys:
![image](https://user-images.githubusercontent.com/34887832/42801837-dd5e9216-8998-11e8-86da-30df2b504326.png)

From the PT sales log we can see sales after the last buys for AION and POE:
![image](https://user-images.githubusercontent.com/34887832/42801933-2ce56f94-8999-11e8-962d-4e07f062938b.png)

PTD seems to have missed these sales even though it was running the whole time; very strange. I assume I will need to cancel and defend these bags again?

**Comment by PTDefenderDev** [comment]
I see why it missed the sell, yesterday one of the things we fixed was partial sells triggering the next round before entire shard was sold. In your case we were waiting for the entire shard to be sold but I see in our logs we had a rounding error so it was off by a very small amount and thought more needed to be sold. I'm writing tests for this case and will push a fix to the backend, thanks again for reporting.

**Comment by PTDefenderDev** [comment]
Okay I'm sorry it wasn't a rounding issue, I've dug in more and it's a stupid bug on my part not multiplying by your max rebuy percentage (50%) for the shard size that we need to wait to sell. Of course almost all the tests I wrote yesterday were at our default of 100% rebuy percentage... Duplicating them with smaller rebuys, will confirm this is covered, and then deploy the fix

**Comment by PTDefenderDev** [comment]
I just more tests for rebuys at 50% and 25%, this was definitely the issue. I just deployed. I'm confident this is handled now so I'm going to close, but please comment if you feel otherwise and I will reopen
