### ISSUE TITLE
Error messages obscured

### ISSUE THREAD

**Issue by lawong88** [PTDefender/Welcome#45]
In V1.6, red error messages are visible when selecting coins in Holdings to Defend, if selection criteria (or insufficient balances) occurs.

In V1.8, no error message are visible, so if selection criteria is incorrect, pressing the Defend button will just revert back.  If closing Defend window, one can see the error message panel disappearing quickly.

Suggestion:  to change error message panel ranking higher than all window panels , optionally to keep error message panel visible until closed.

**Comment by PTDefenderDev** [comment]
Thanks for reporting, I just fixed this it will be released in the next day or so

**Comment by PTDefenderDev** [comment]
Released: https://github.com/PTDefender/Welcome/releases/tag/1.9.0
