### ISSUE TITLE
Security Issue on PT Defender with Binance!

### ISSUE THREAD

**Issue by des1re10** [PTDefender/Welcome#47]
Hello Support Team,

There is an security issue while you are using PT Defender in combination with Binance!
In that case you actually have to add that IP Address to the Binance API settings: 34.233.244.208, while there is IP Address restriction enabled (really recommended).

Unfortunately that IP Address is listed as illegal on Binance!

That means you can only disable IP restriction on Binance so far. But that would be an security issue!

Please make sure your necessary IP Address "34.233.244.208" can be used safely with Binance.

Thanks in advance!

Best regards,
Robert

**Comment by PTDefenderDev** [comment]
Hey I think you just typed it in wrong... Please make sure there are no spaces at all, Example:

```
123.456.78.90,34.233.244.208
```

**Comment by des1re10** [comment]
Ah youre right! My bad :) Thank you very much!

Best regards,
