### ISSUE TITLE
Doesn't work on a Raspberry Pi

### ISSUE THREAD

**Issue by SlumdogTrader** [PTDefender/Welcome#5]
You state in FAQs that:

> Is my operating system supported?, Yes, PTDefender will work on any operating system that ProfitTrailer Supports.

Yet it is not supported on a Raspberry Pi, even though PT Supports it. The Linux file is an ARM64 and to run on a Raspberry Pi it needs to be armhf. 

I bought it on this statement - I either want a full refund or a working file to support Raspberry Pi.

**Comment by PTDefenderDev** [comment]
@SlumdogTrader I'm really sorry about that, definitely misleading. I've been building this for around 2 months and 99% of the testing has been on macOS, Windows and ubuntu. It should definitely be possible to run this on Pi, its built with [Electron](https://electronjs.org) (developed by GitHub) which supports Arm/Pi applications but I need do a bit more reading on how to compile it properly. If you'd like a refund happy to make the happen. Just need to know how you paid (crypto or credit card) and what email address you used. If you paid with crypto, please send me an address to send the funds to.

**Comment by PTDefenderDev** [comment]
Please email me at dev@ptdefender.com for the refund info, don't want it Public here

**Comment by SlumdogTrader** [comment]
Hi - thanks for quick response. I dont want a refund (dont want to pay extra $50) plus I will see if I can get my Pi using ARM64 (through a backdoor kernel or something like Docker???) It will be if then PT etc works on that kernel. If in the meantime you get it compiled for Pi I'd love to know - 64 will slow my pi down considerably and I'd rather use stock kernel for speed. Cheers

**Comment by SlumdogTrader** [comment]
Hi developer,

This might help with your OS problems 

https://electronjs.org/docs/development/build-instructions-linux

its explains cross compilation, and also maybe help on CentOS. Thought I might as well try and help with a solution. If you need me for testing etc then let me know, more than happy to help.
