### ISSUE TITLE
Drop down list for license key

### ISSUE THREAD

**Issue by LarsK81** [PTDefender/Welcome#51]
Hi guys,

my graphics interface doesn´t allow me to copy and paste the license key, could you implement a drop down so that I don´t have to enter the license key every time manually. It´s really a nuisance. 

Cheers Lars

**Comment by PTDefenderDev** [comment]
Hey Lars, is that app not saving your license when you close it? Or are you starting a lot of new sessions? Curious why you'd be ending up at the activation screen that frequently to begin with.

I can look at a building a drowdown with previously entered licenses, wouldn't be too bad.

**Comment by LarsK81** [comment]
Every time, I update the version I have to put in the key, and I have 3 bots running, so each time I log off the key again. I´m using this MacOS tool to connect.
![ptd](https://user-images.githubusercontent.com/39250982/43436398-b91e8afc-94c7-11e8-8af0-4feccc126062.png)

**Comment by LarsK81** [comment]
See, I open a new session and I have to enter the key again for my second bot. :(
![ptd2](https://user-images.githubusercontent.com/39250982/43436569-5012bdb6-94c8-11e8-9077-1a6b423540df.png)

**Comment by PTDefenderDev** [comment]
Instead of a dropdown I'm just going to pre-fill your license when you start a new session. Hopefully that helps for now. This will be released later today or tomorrow
