### ISSUE TITLE
Defended Pairs show in Holdings 

### ISSUE THREAD

**Issue by vbootstrap** [PTDefender/Welcome#6]
An already defended pair still shows in the holding section with a start button next to it.  I would think that the defend button would not be available next to a holding that is already being defended.

**Comment by vbootstrap** [comment]
will this also prevent it from actually defending the configured pairs?  If so what is the expected ETA of the update?

**Comment by PTDefenderDev** [comment]
Just released in v1.0.7: https://www.ptdefender.com/download
