### ISSUE TITLE
Failed to start defending undefined

### ISSUE THREAD

**Issue by scroll1** [PTDefender/Welcome#7]
Hi,
I keep getting the above error whenever I try to start defending a coin. The defending settings screen does not close, but the coin does go into the defending list, and PT removes the coin from DCA, and a pending order is placed. I have tried restarting the app. I am on a Linux VPS. Thanks.

**Comment by PTDefenderDev** [comment]
Looking into this now. It takes a full 10 seconds to start defending a coin and then the overlay should go away. Seems like something is preventing that, do you see any visible error messages on the screen?

**Comment by scroll1** [comment]
Only the error message:
Failed to start defending undefined

If I go into the defending section and choose to stop, I get the same error. But it does stop it.

**Comment by PTDefenderDev** [comment]
Okay that tells me it's an issue setting the hotconfig on ProfitTrailer. What version of ProfitTrailer are you using? It's best to use the latest version 2.0.13

**Comment by scroll1** [comment]
Yep. Using 2.0.13
I have a screen shot of the error in the discord channel. Can't seem to add it to this discussion.
It's under the user brennanlabs

**Comment by PTDefenderDev** [comment]
Can you shoot me an email at dev@ptdefender.com? I need to see your application.properties file, my guess is there's a space at the end of the license or something thats messing it up. I need to handle better on my end but first want to confirm thats it

**Comment by scroll1** [comment]
sorry, not comfortable sending you that file containing my license. I'll double-check for any spacing after the license though. I can send you the file minus the license once I get back home in a few hours. I'll get back to you on that.

**Comment by PTDefenderDev** [comment]
Yup no I problem, I understand. I just released version 1.0.8 which should handle extra spacing in that file. If that was the issue, this version should fix it: https://www.ptdefender.com/download

**Comment by scroll1** [comment]
I don't have a space after the license. There is a space before the license after the =  sign
I did find an error in my timezone setting (a symbol that shouldn't have been there) but I'm not sure if that would have thrown up that error

**Comment by scroll1** [comment]
finally got a chance to install to the latest update, the error message does not seem to happen any more and the settings page disappears after a few seconds. thanks for your help
