### ISSUE TITLE
Automation of Start/Stop Defending

### ISSUE THREAD

**Issue by Dictatosaur** [PTDefender/Welcome#8]
I've had a bag of BCC/USDT (on Binance), yesterday it was at -5%, today BCC surged up by 10% +-, most of the bag was in pending and sold at 1% profit (as according to my Defender settings). 

1% is not bad, but it could have been more. 
If at some point the bag went from pending to PAIRS or DCA, ProfitTrailer would've sold the bag at a higher profit than Defender.

PS:
The pending bag was sold **before** ProfitTrailer sold the small chunk it was given by Defender.

**Comment by PTDefenderDev** [comment]
Definitely on our roadmap, will update this issue as we make more progress

**Comment by WolfieGang** [comment]
thank you for the input we have this in works

**Comment by PTDefenderDev** [comment]
Officially released: https://github.com/PTDefender/Welcome/releases/tag/1.10.0
