### ISSUE TITLE
Defender still defending after "pending" and "chunk" sold

### ISSUE THREAD

**Issue by Dictatosaur** [PTDefender/Welcome#9]
Had to manually stop Defending after pair was sold.

**Comment by Dictatosaur** [comment]
Target % : -0.5
Rebuy: 100
Gain: 1.0
Action: Hold

(This was on version 1.0.6 )

After Binance executed the limit order and Profit Trailer sold the small "chunk", the bag (the pending limit order Defender opened) was still visible is "Defending".

Once I've stopped Defending, it disappeared.

**Comment by PTDefenderDev** [comment]
New version with logs tab: https://github.com/PTDefender/Welcome/releases/tag/1.2.0
